import Head from "next/head";
import Homepage from "../components/home/Homepage";
export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Veltio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
    </div>
  );
}
